export const emojis: { [index: string]: string } = {
  "😊": "smile",
  "🙃": "upside_down",
  "🤪": "quirky",
  "🤓": "nerd",
  "🤯": "mind_blown",
  "😴": "sleep",
  "💩": "poop",
  "👻": "ghost",
  "👽": "alien",
  "🤖": "robot",
  "👾": "game",
  "👐": "open",
  "🖖": "vulkan",
  "✌️": "peace",
  "🤟": "love",
  "🤘": "rock",
  "🤙": "call",
  "👋": "wave",
  "🐭": "rat",
  "🦕": "dino",
  "🦖": "t_rex",
  "🐉": "dragon",
  "🤡": "clown",
};
